from enum import Enum


class AssetsListOItem(str, Enum):
    ASSET_MANAGER = "asset_manager"
    ASSET_MANAGER_FIRST_NAME = "asset_manager__first_name"
    ASSET_MANAGER_LAST_NAME = "asset_manager__last_name"
    ASSET_NUMERIC_GRADE = "asset_numeric_grade"
    BUSINESS_CRITICALITY = "business_criticality"
    CREATED = "created"
    EXTERNAL_AUDIENCE = "external_audience"
    ID = "id"
    INTERNET_ACCESSIBLE = "internet_accessible"
    LIFECYCLE = "lifecycle"
    NAME = "name"
    ORGANIZATION = "organization"
    ORGANIZATION_NAME = "organization__name"
    ORIGIN = "origin"
    PLATFORM = "platform"
    REVENUE = "revenue"
    TEAM_MANAGER = "team_manager"
    TEAM_MANAGER_FIRST_NAME = "team_manager__first_name"
    TEAM_MANAGER_LAST_NAME = "team_manager__last_name"
    TECHNICAL_CONTACT = "technical_contact"
    TECHNICAL_CONTACT_FIRST_NAME = "technical_contact__first_name"
    TECHNICAL_CONTACT_LAST_NAME = "technical_contact__last_name"
    TID = "tid"
    UPDATED = "updated"
    USER_RECORDS = "user_records"
    VALUE_0 = "-asset_manager"
    VALUE_1 = "-asset_manager__first_name"
    VALUE_10 = "-name"
    VALUE_11 = "-organization"
    VALUE_12 = "-organization__name"
    VALUE_13 = "-origin"
    VALUE_14 = "-platform"
    VALUE_15 = "-revenue"
    VALUE_16 = "-team_manager"
    VALUE_17 = "-team_manager__first_name"
    VALUE_18 = "-team_manager__last_name"
    VALUE_19 = "-technical_contact"
    VALUE_2 = "-asset_manager__last_name"
    VALUE_20 = "-technical_contact__first_name"
    VALUE_21 = "-technical_contact__last_name"
    VALUE_22 = "-tid"
    VALUE_23 = "-updated"
    VALUE_24 = "-user_records"
    VALUE_3 = "-asset_numeric_grade"
    VALUE_4 = "-business_criticality"
    VALUE_5 = "-created"
    VALUE_6 = "-external_audience"
    VALUE_7 = "-id"
    VALUE_8 = "-internet_accessible"
    VALUE_9 = "-lifecycle"

    def __str__(self) -> str:
        return str(self.value)
